# Generated by Django 5.2.7 on 2025-10-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
