# Generated by Django 5.2.7 on 2025-10-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
