# Generated by Django 5.2.7 on 2025-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descripción para SEO (máx. 300 caracteres)', null=True, verbose_name='Meta Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para SEO (máx. 200 caracteres)', max_length=200, null=True, verbose_name='Meta Título'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_threshold',
            field=models.IntegerField(default=5, help_text='Nivel de stock para alertas (default: 5)', verbose_name='Umbral de Stock Bajo'),
        ),
    ]
