"""
Django settings for E_commerce_proyecto project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-61qg33e6@xz0e2n3c%b)4tc-#y16spye7xg!$ndz=ph30r*fu5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'orders',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'E_commerce_proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'E_commerce_proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------
# Configuraciones de Autenticación
# --------------------

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login' # Define la URL para la vista de login

# --------------------
# Configuraciones de Archivos de Medios (Imágenes)
# --------------------

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --------------------
# Configuraciones de Email para reseteo de contraseña
# --------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mautodano2000@gmail.com' # <--- CAMBIA ESTO
EMAIL_HOST_PASSWORD = 'naeo cqnl lvug qfvj' # <--- CAMBIA ESTO (usa una contraseña de aplicación)

# Puedes usar esta configuración para probar el correo en la consola
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Definición de una tarifa de envío fija para el MVP.
SHIPPING_FEE = 5.00

# --------------------------------------------------------------------------
# CONFIGURACIÓN DE PAGO - SPRINT 2 (Stripe)
# --------------------------------------------------------------------------

# Clave de API Secreta de Stripe (Modo Testing)
# DEBES REEMPLAZAR ESTE VALOR con tu clave de prueba (ej: sk_test_...)
STRIPE_SECRET_KEY = 'sk_test_51SDolF3ElVeomltG3CnOJsud9qu4on9E3BsJnFw7EA04dbCxglKuqk1dTmzRdvKknwRDN3Xisnq1aBIHqyUDAJb80059ZuqbO4'

# Clave de API Pública de Stripe (Modo Testing)
# DEBES REEMPLAZAR ESTE VALOR con tu clave publicable (ej: pk_test_...)
STRIPE_PUBLIC_KEY = 'pk_test_51SDolF3ElVeomltG9wFzIlcUo9RI89KxPuzj2MPsxDlIzPqMShOjwOYJ4Q3xlmdppnYR0ShFwzsHoKzzoUwcOC8Z00vw9OevDs'

# Clave Secreta del Webhook de Stripe
# Este es un valor que Stripe genera al configurar tu webhook
STRIPE_WEBHOOK_SECRET = 'WH_CLAVE_SECRETA_DEL_WEBHOOK'

# Moneda base de la tienda (ej: 'usd', 'eur', 'mxn')
DEFAULT_CURRENCY = 'usd'
